# codacy configuration file

---

engines:
    coverage:
        enabled: true
        exclude_paths: [
            'tests',
        ]
    metrics:
        enabled: true
    duplication:
        enabled: true
    prospector:
        enabled: true

exclude_paths: [
    'doc/sphinx/**',
    'esmvaltool/cmor/tables/**',
    'tests/**'
]
