---
name: esmvaltool
channels:
  # The release candidate channel should only be activated
  # during the rc phase right before the next release of the
  # ESMValCore.
  # - conda-forge/label/esmvalcore_rc
  - conda-forge
  - nodefaults

dependencies:
  - pip!=21.3
  - python>=3.8
  # Python packages that cannot be installed from PyPI:
  - cartopy
  - compilers
  - esmpy
  - esmvalcore
  - gdal
  - matplotlib-base
  # Non-Python dependencies
  - cdo
  - imagemagick
  - julia
  - nco
  - psyplot
  - psy-maps
  - psy-reg
  - psy-simple
  - python-cdo
  - rasterio
  - ruamel.yaml
  - scikit-learn  # may hit hw-specific issue if from pypi https://github.com/scikit-learn/scikit-learn/issues/14485
  - xgboost

  # Multi language support:
  - ncl
  - r-base
  # R packages needed for development
  - r-abind
  - r-akima<=0.6-2.3
  - r-climdex.pcic
  - r-ClimProjDiags
  - r-docopt
  - r-functional
  - r-ggplot2
  - r-git2r  # dependency of lintr
  - r-gridExtra  
  - r-lintr
  - r-logging
  - r-mapproj
  - r-maps
  - r-multiApply
  - r-ncdf4
  - r-ncdf4.helpers
  - r-PCICt
  - r-plyr
  - r-RColorBrewer
  - r-Rcpp
  - r-s2dverification
  - r-snow
  - r-SPEI
  - r-styler
  - r-yaml
  - r-udunits2  # needed by the docker build
