---

name: esmvaltool
channels:
  - conda-forge

dependencies:
  # Python packages that cannot be installed from PyPI:
  - iris
  - matplotlib<3  # Can be installed from PyPI, but is a dependency of iris and should be pinned.
  - python-stratify
  - esmpy
  - xarray  # Can be installed from PyPI, but here to get a consistent set of depencies with iris.
  # Non-Python dependencies
  - graphviz
  - cdo=1.9.3
  # Installation fails when used directly with pip
  - pip:
    - "git+https://github.com/datascienceinc/Skater.git#egg=Skater"

  # Multi language support:
  - ncl
  - jasper!=1.900.31  # pinned NCL dependency
  - r-base
  - r-rcpp
  - r-xml
  - libunwind  #  specifically for Python3.7+
  # TODO: add julia
