# recipe_mlr_co2_scalar.yml
---
documentation:

  description: |
    Use MLR (Machine Learning Regression) models to predict future CO2 fluxes
    scalar diagnostics.

  authors:
    - schl_ma

  maintainer:
    - schl_ma

  projects:
    - crescendo


DATASET_ANCHOR: &datasets
  - {dataset: BNU-ESM}
  - {dataset: CanESM2}
  - {dataset: CCSM4}
  - {dataset: CESM1-BGC}
  # - {dataset: CESM1-FASTCHEM}
  # - {dataset: CESM1-WACCM}
  # - {dataset: CMCC-CESM}
  # - {dataset: GFDL-ESM2G}
  - {dataset: GFDL-ESM2M}
  - {dataset: HadGEM2-CC}
  - {dataset: HadGEM2-ES}
  # - {dataset: inmcm4}
  # - {dataset: IPSL-CM5A-LR}
  # - {dataset: IPSL-CM5A-MR}
  # - {dataset: IPSL-CM5B-LR}
  # - {dataset: MIROC-ESM}
  # - {dataset: MIROC-ESM-CHEM}
  # - {dataset: MPI-ESM-LR}
  # - {dataset: MPI-ESM-MR}
  # # - {dataset: MPI-ESM-P}
  # # - {dataset: MRI-ESM1}
  # - {dataset: NorESM1-M}
  # - {dataset: NorESM1-ME}


preprocessors:

  landmask: &landmask
    mask_landsea:
      mask_out: sea
    extract_region:
      start_latitude: -60.0
      end_latitude: 90.0
      start_longitude: 0.0
      end_longitude: 360.0

  landmask_average:
    <<: *landmask
    area_statistics:
      operator: mean


diagnostics:

  diag_mlr_input_tas:
    variables:
      features: &variable_settings
        short_name: tas
        preprocessor: landmask_average
        project: CMIP5
        mip: Amon
        exp: historical
        ensemble: r1i1p1
        start_year: 1985
        end_year: 2005
        var_type: feature
        additional_datasets: *datasets
      prediction_input:
        <<: *variable_settings
        var_type: prediction_input
        additional_datasets:
          - {dataset: CRU, project: OBS, type: reanaly, version: TS4.02, tier: 2}
    scripts:
      mean: &mean
        script: mlr/preprocess.py
        mean: ['time']
        tag: T-Glob_c
        convert_units_to: celsius
      trend: &trend
        script: mlr/preprocess.py
        trend: year
        tag: T-Glob_t

  diag_mlr_input_pr:
    variables:
      features:
        <<: *variable_settings
        short_name: pr
      prediction_input:
        <<: *variable_settings
        short_name: pr
        var_type: prediction_input
        additional_datasets:
          - {dataset: CRU, project: OBS, type: reanaly, version: TS4.02, tier: 2}
    scripts:
      mean:
        <<: *mean
        tag: PR-Glob_c
        convert_units_to: 'kg m-2 day-1'
      trend:
        <<: *trend
        tag: PR-Glob_t
        convert_units_to: 'kg m-2 day-1 year-1'

  diag_mlr_input_rsds:
    variables:
      features:
        <<: *variable_settings
        short_name: rsds
        start_year: 2001
      prediction_input:
        <<: *variable_settings
        short_name: rsds
        start_year: 2001
        var_type: prediction_input
        additional_datasets:
          - {dataset: CERES-EBAF, project: obs4mips, level: L3B, version: Ed2-7, tier: 1}
    scripts:
      mean:
        <<: *mean
        tag: SSRD-Glob_c
        convert_units_to: null
      trend:
        <<: *trend
        tag: SSRD-Glob_t
        convert_units_to: null

  diag_mlr_input_rsus:
    variables:
      features:
        <<: *variable_settings
        short_name: rsus
        start_year: 2001
      prediction_input:
        <<: *variable_settings
        short_name: rsus
        start_year: 2001
        var_type: prediction_input
        additional_datasets:
          - {dataset: CERES-EBAF, project: obs4mips, level: L3B, version: Ed2-7, tier: 1}
    scripts:
      mean:
        <<: *mean
        tag: SSRU-Glob_c
        convert_units_to: null
      trend:
        <<: *trend
        tag: SSRU-Glob_t
        convert_units_to: null

  diag_mlr_input_rlds:
    variables:
      features:
        <<: *variable_settings
        short_name: rlds
        start_year: 2001
      prediction_input:
        <<: *variable_settings
        short_name: rlds
        start_year: 2001
        var_type: prediction_input
        additional_datasets:
          - {dataset: CERES-EBAF, project: obs4mips, level: L3B, version: Ed2-7, tier: 1}
    scripts:
      mean:
        <<: *mean
        tag: SLRD-Glob_c
        convert_units_to: null
      trend:
        <<: *trend
        tag: SLRD-Glob_t
        convert_units_to: null

  diag_mlr_input_rlus:
    variables:
      features:
        <<: *variable_settings
        short_name: rlus
        start_year: 2001
      prediction_input:
        <<: *variable_settings
        short_name: rlus
        start_year: 2001
        var_type: prediction_input
        additional_datasets:
          - {dataset: CERES-EBAF, project: obs4mips, level: L3B, version: Ed2-7, tier: 1}
    scripts:
      mean:
        <<: *mean
        tag: SLRU-Glob_c
        convert_units_to: null
      trend:
        <<: *trend
        tag: SLRU-Glob_t
        convert_units_to: null

  diag_mlr_input_et:
    variables:
      features:
        <<: *variable_settings
        short_name: et
        mip: Lmon
        start_year: 1989
        derive: true
      prediction_input:
        <<: *variable_settings
        short_name: et
        mip: Lmon
        start_year: 1989
        derive: true
        var_type: prediction_input
        additional_datasets:
          - {dataset: LandFlux-EVAL, project: OBS, type: reanaly, version: Oct13, tier: 3}
    scripts:
      mean:
        <<: *mean
        tag: ET-Glob_c
        convert_units_to: null
      trend:
        <<: *trend
        tag: ET-Glob_t
        convert_units_to: null

  # diag_mlr_input_cVeg:
  #   variables:
  #     features: &variable_settings_flux
  #       <<: *variable_settings
  #       short_name: cVeg_grid
  #       preprocessor: landmask
  #       mip: Lmon
  #       derive: true
  #     prediction_input:
  #       <<: *variable_settings_flux
  #       var_type: prediction_input
  #       additional_datasets:
  #         - {dataset: NDP, project: OBS, type: ground, version: 017b, tier: 2, start_year: 2000, end_year: 2000}
  #   scripts:
  #     mean: &mean_flux
  #       <<: *mean
  #       sum: ['latitude', 'longitude']
  #       tag: CVEG-Glob_c
  #       convert_units_to: 'Gt'

  # diag_mlr_input_cSoil:
  #   variables:
  #     features:
  #       <<: *variable_settings_flux
  #       short_name: cSoil_grid
  #     prediction_input:
  #       <<: *variable_settings_flux
  #       short_name: cSoil_grid
  #       var_type: prediction_input
  #       additional_datasets:
  #         - {dataset: HWSD, project: OBS, type: ground, version: 1, tier: 2, start_year: 2000, end_year: 2000}
  #   scripts:
  #     mean:
  #       <<: *mean_flux
  #       tag: CSOIL-Glob_c
  #       convert_units_to: 'Gt'

  # diag_mlr_input_nbp:
  #   variables:
  #     features:
  #       <<: *variable_settings_flux
  #       short_name: nbp_grid
  #     prediction_input:
  #       <<: *vnariable_settings_flux
  #       short_name: nbp_grid
  #       var_type: prediction_input
  #       additional_datasets:
  #         - {dataset: JMA-TRANSCOM, project: OBS, type: reanaly, version: 1, tier: 3}
  #     label:
  #       <<: *variable_settings_flux
  #       short_name: nbp_grid
  #       exp: rcp45
  #       start_year: 2020
  #       end_year: 2039
  #       var_type: label
  #   scripts:
  #     mean:
  #       <<: *mean_flux
  #       tag: NBP-Glob_c
  #       convert_units_to: 'Gt yr-1'

  diag_mlr_input_gpp:
    variables:
      features: &variable_settings_flux
        <<: *variable_settings
        short_name: gpp_grid
        preprocessor: landmask
        mip: Lmon
        derive: true
      prediction_input:
        <<: *variable_settings_flux
        short_name: gpp_grid
        var_type: prediction_input
        additional_datasets:
          - {dataset: MTE, project: OBS, type: reanaly, version: May12, tier: 3}
      label:
        <<: *variable_settings_flux
        short_name: gpp_grid
        exp: rcp45
        start_year: 2020
        end_year: 2039
        var_type: label
    scripts:
      mean: &mean_flux
        <<: *mean
        sum: ['latitude', 'longitude']
        tag: GPP-Glob_c
        convert_units_to: 'Gt yr-1'

  diag_mlr_input_lai:
    variables:
      features:
        <<: *variable_settings_flux
        short_name: lai_grid
        preprocessor: landmask_average
      prediction_input:
        <<: *variable_settings_flux
        short_name: lai_grid
        preprocessor: landmask_average
        var_type: prediction_input
        additional_datasets:
          - {dataset: LAI3g, project: OBS, type: reanaly, version: 1_regridded, tier: 3}
    scripts:
      mean:
        <<: *mean
        tag: LAI-Glob_c
        convert_units_to: null
      trend:
        <<: *trend
        tag: LAI-Glob_t
        convert_units_to: null

  diag_mlr:
    description: Perform MLR on input data.
    scripts:
      mlr:
        script: mlr/main.py
        ancestors: [
          'diag_mlr_input_*/mean',
          'diag_mlr_input_*/trend',
        ]
        mlr_model: gpr_george
        accept_only_scalar_data: true
        allow_missing_features: true
        group_datasets_by_attributes: ['dataset', 'ensemble']
        imputation_strategy: mean
        parameters_final_regressor:
          n_estimators: 100
          subsample: 0.5
          learning_rate: 0.1
          max_depth: 6
