# recipe_mlr_austral_jet.yml
---
documentation:

  description: |
    Use MLR (Machine Learning Regression) models to predict future austral jet
    position for multidimensional diagnostics.

  authors:
    - schl_ma

  maintainer:
    - schl_ma

  projects:
    - crescendo


preprocessors:

  time_average:
    time_average: null

  external_ua:
    time_average: null
    extract_levels:
      levels: 100000
      scheme: linear


diagnostics:

  diag_external_ua:
    variables:
      ua_feature: &ext_variable_settings
        short_name: ua
        project: CMIP5
        mip: Amon
        field: T3M
        exp: historical
        ensemble: r1i1p1
        start_year: 2000
        end_year: 2000
        preprocessor: external_ua
        tag: EXTERNAL_UA
        var_type: feature
        broadcast_from: [1, 2]
        additional_datasets: &datasets
          # - {dataset: CanESM2}
          - {dataset: IPSL-CM5A-LR}
          # - {dataset: MIROC5}
          # - {dataset: MIROC-ESM}
          # - {dataset: MPI-ESM-LR}
          # - {dataset: NorESM1-M}
      ua_prediction_input:
        <<: *ext_variable_settings
        var_type: prediction_input
        additional_datasets:
          - {dataset: ERA-Interim, project: OBS, type: reanaly, version: 1, tier: 3}
    scripts:
      null

  diag_mlr:
    description: Perform MLR on input data.
    variables:
      feature_ta: &variable_settings
        short_name: ta
        project: CMIP5
        mip: Amon
        field: T3M
        exp: historical
        ensemble: r1i1p1
        start_year: 1979
        end_year: 2005
        preprocessor: time_average
        tag: T
        var_type: feature
        additional_datasets: *datasets
      prediction_input_ta:
        <<: *variable_settings
        var_type: prediction_input
        additional_datasets:
          - {dataset: ERA-Interim, project: OBS, type: reanaly, version: 1, tier: 3}
      feature_tas:
        <<: *variable_settings
        short_name: tas
        field: T2Ms
        tag: TAS
        broadcast_from: [1, 2]
      prediction_input_tas:
        <<: *variable_settings
        short_name: tas
        field: T2Ms
        tag: TAS
        var_type: prediction_input
        broadcast_from: [1, 2]
        additional_datasets:
          - {dataset: ERA-Interim, project: OBS, type: reanaly, version: 1, tier: 3}
      feature_ua:
        short_name: ua
        <<: *variable_settings
        tag: UA
      prediction_input_ua:
        <<: *variable_settings
        short_name: ua
        tag: UA
        var_type: prediction_input
        additional_datasets:
          - {dataset: ERA-Interim, project: OBS, type: reanaly, version: 1, tier: 3}
      label:
        <<: *variable_settings
        short_name: ua
        exp: rcp45
        start_year: 2015
        end_year: 2034
        tag: UA
        var_type: label
    scripts:
      multiple_mlr_models:
        script: mlr/multiple_mlr_models.py
        ancestors: ['feature_*', 'prediction_input_*', 'label',
                    'diag_external_ua/*']
        model: gbr
        imputation_strategy: mean
        use_coords_as_feature:
          air_pressure: 0
          latitude: 1
          longitude: 2
        metadata_preselection:
          select:
            project: CMIP5
          group: dataset
        parameters: &params
          learning_rate: 0.01
          loss: ls
          max_depth: 4
          min_samples_split: 2
          n_estimators: 2000
      single_mlr_model:
        script: mlr/single_mlr_model.py
        ancestors: ['feature_*', 'prediction_input_*', 'label',
                    'diag_external_ua/*']
        mlr_model: gbr
        imputation_strategy: mean
        use_coords_as_feature:
          air_pressure: 0
          latitude: 1
          longitude: 2
        group_datasets_by_attributes: ['dataset']
        parameters: *params

  diag_austral_jet_position:
    description: Calculate Austral Jet position.
    scripts:
      austral_jet_position:
        script: austral_jet/jet_position.py
        ancestors: [
          'diag_mlr/multiple_mlr_models',
          'diag_mlr/single_mlr_model',
        ]
