# recipe_mlr_austral_jet_scalar.yml
---
documentation:

  description: |
    Use MLR (Machine Learning Regression) models to predict future austral jet
    position for scalar diagnostics.

  authors:
    - schl_ma

  maintainer:
    - schl_ma

  projects:
    - crescendo


DATASET_ANCHOR: &datasets
  - {dataset: ACCESS1-0,      ensemble: r1i1p1}
  - {dataset: ACCESS1-3,      ensemble: r1i1p1}


  # - {dataset: bcc-csm1-1,     ensemble: r1i1p1}


  - {dataset: BNU-ESM,        ensemble: r1i1p1}
  - {dataset: CanESM2,        ensemble: r1i1p1}
  - {dataset: CanESM2,        ensemble: r2i1p1}
  - {dataset: CanESM2,        ensemble: r3i1p1}
  - {dataset: CanESM2,        ensemble: r4i1p1}
  - {dataset: CanESM2,        ensemble: r5i1p1}


  # - {dataset: CCSM4,          ensemble: r1i1p1}
  # - {dataset: CCSM4,          ensemble: r2i1p1}
  # - {dataset: CCSM4,          ensemble: r3i1p1}
  # - {dataset: CCSM4,          ensemble: r4i1p1}
  # - {dataset: CCSM4,          ensemble: r5i1p1}
  # - {dataset: CCSM4,          ensemble: r6i1p1}


  - {dataset: CESM1-BGC,      ensemble: r1i1p1}
  - {dataset: CESM1-CAM5,     ensemble: r1i1p1}
  - {dataset: CESM1-CAM5,     ensemble: r2i1p1}
  - {dataset: CESM1-CAM5,     ensemble: r3i1p1}
  - {dataset: CMCC-CMS,       ensemble: r1i1p1}
  - {dataset: CNRM-CM5,       ensemble: r1i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r1i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r2i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r3i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r4i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r5i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r6i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r7i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r8i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r9i1p1}
  - {dataset: CSIRO-Mk3-6-0,  ensemble: r10i1p1}
  - {dataset: GFDL-CM3,       ensemble: r1i1p1}
  - {dataset: GFDL-ESM2G,     ensemble: r1i1p1}
  - {dataset: GFDL-ESM2M,     ensemble: r1i1p1}
  - {dataset: HadGEM2-AO,     ensemble: r1i1p1}
  - {dataset: inmcm4,         ensemble: r1i1p1}
  - {dataset: IPSL-CM5A-LR,   ensemble: r1i1p1}
  - {dataset: IPSL-CM5A-LR,   ensemble: r2i1p1}
  - {dataset: IPSL-CM5A-LR,   ensemble: r3i1p1}
  - {dataset: IPSL-CM5A-LR,   ensemble: r4i1p1}
  - {dataset: IPSL-CM5A-MR,   ensemble: r1i1p1}
  - {dataset: IPSL-CM5B-LR,   ensemble: r1i1p1}
  - {dataset: MIROC5,         ensemble: r1i1p1}
  - {dataset: MIROC5,         ensemble: r2i1p1}
  - {dataset: MIROC-ESM,      ensemble: r1i1p1}
  - {dataset: MIROC-ESM-CHEM, ensemble: r1i1p1}
  - {dataset: MPI-ESM-LR,     ensemble: r1i1p1}
  - {dataset: MPI-ESM-LR,     ensemble: r2i1p1}
  - {dataset: MPI-ESM-LR,     ensemble: r3i1p1}
  - {dataset: MPI-ESM-MR,     ensemble: r1i1p1}
  - {dataset: MPI-ESM-MR,     ensemble: r2i1p1}
  - {dataset: MPI-ESM-MR,     ensemble: r3i1p1}
  - {dataset: MRI-CGCM3,      ensemble: r1i1p1}
  - {dataset: NorESM1-M,      ensemble: r1i1p1}


preprocessors:

  noop:
    {}

  sp50:
    extract_month:
      month: [9, 10, 11, 12]
    extract_levels:
      levels: 5000
      scheme: linear
    extract_region:
      start_latitude: -90
      end_latitude: -60
      start_longitude: 0
      end_longitude: 360
    area_statistics:
      operator: mean

  sp100:
    extract_month:
      month: [10, 11, 12, 1]
    extract_levels:
      levels: 10000
      scheme: linear
    extract_region:
      start_latitude: -90
      end_latitude: -60
      start_longitude: 0
      end_longitude: 360
    area_statistics:
      operator: mean

  ng50:
    extract_levels:
      levels: 5000
      scheme: linear
    extract_region:
      start_latitude: -82.5
      end_latitude: 82.5
      start_longitude: 0
      end_longitude: 360
    area_statistics:
      operator: mean

  ng100:
    extract_levels:
      levels: 10000
      scheme: linear
    extract_region:
      start_latitude: -90
      end_latitude: 90
      start_longitude: 0
      end_longitude: 360
    area_statistics:
      operator: mean

  trop250:
    extract_month:
      month: [12, 1, 2]
    extract_levels:
      levels: 25000
      scheme: linear
    extract_region:
      start_latitude: -30
      end_latitude: 30
      start_longitude: 0
      end_longitude: 360
    area_statistics:
      operator: mean

  djf:
    extract_month:
      month: [12, 1, 2]

  time_average_djf:
    extract_month:
      month: [12, 1, 2]
    time_average: null


diagnostics:

  diag_mlr_input_ta_sp100:
    variables:
      ta: &variable_settings
        project: CMIP5
        mip: Amon
        exp: historical
        start_year: 1979
        end_year: 2005
        preprocessor: sp100
        var_type: feature
        additional_datasets:
          - {dataset: ERA-Interim, project: OBS, type: reanaly, version: 1, tier: 3, var_type: prediction_input}
    additional_datasets: *datasets
    scripts:
      mean: &mean
        script: mlr/simple_pp.py
        mean: ['time']
        tag: T-SP_c
      trend: &trend
        script: mlr/simple_pp.py
        trend: year
        tag: T-SP_t

  diag_mlr_input_ta_ng100:
    variables:
      ta:
        <<: *variable_settings
        preprocessor: ng100
    additional_datasets: *datasets
    scripts:
      mean:
        <<: *mean
        tag: T-NGlob_c
      trend:
        <<: *trend
        tag: T-NGlob_t

  diag_mlr_input_ta_trop250:
    variables:
      ta:
        <<: *variable_settings
        preprocessor: trop250
    additional_datasets: *datasets
    scripts:
      mean:
        <<: *mean
        tag: T-Trop_c
      trend:
        <<: *trend
        tag: T-Trop_t

  # diag_mlr_input_tro3_sp50:
  #   variables:
  #     tro3:
  #       <<: *variable_settings
  #       preprocessor: sp50
  #       additional_datasets:
  #         - {dataset: BDBP, project: OBS, type: reanaly, version: 1, tier: 3, var_type: prediction_input}
  #   additional_datasets: &tro3_datasets
  #     - {dataset: ACCESS1-0,      project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: ACCESS1-3,      project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: CESM1-BGC,      project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: CESM1-CAM5,     project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: CESM1-CAM5,     project: Ozone_CMIP5_ACC_SPARC, ensemble: r2i1p1}
  #     - {dataset: CESM1-CAM5,     project: Ozone_CMIP5_ACC_SPARC, ensemble: r3i1p1}
  #     - {dataset: CMCC-CMS,       project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r2i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r3i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r4i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r5i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r6i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r7i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r8i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r9i1p1}
  #     - {dataset: CSIRO-Mk3-6-0,  project: Ozone_CMIP5_ACC_SPARC, ensemble: r10i1p1}
  #     - {dataset: HadGEM2-AO,     project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: inmcm4,         project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: MRI-CGCM3,      project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     - {dataset: NorESM1-M,      project: Ozone_CMIP5_ACC_SPARC, ensemble: r1i1p1}
  #     # - {dataset: bcc-csm1-1,     ensemble: r1i1p1}
  #     - {dataset: BNU-ESM,        ensemble: r1i1p1}
  #     - {dataset: CanESM2,        ensemble: r1i1p1}
  #     - {dataset: CanESM2,        ensemble: r2i1p1}
  #     - {dataset: CanESM2,        ensemble: r3i1p1}
  #     - {dataset: CanESM2,        ensemble: r4i1p1}
  #     - {dataset: CanESM2,        ensemble: r5i1p1}
  #     # - {dataset: CCSM4,          ensemble: r1i1p1}
  #     # - {dataset: CCSM4,          ensemble: r2i1p1}
  #     # - {dataset: CCSM4,          ensemble: r3i1p1}
  #     # - {dataset: CCSM4,          ensemble: r4i1p1}
  #     # - {dataset: CCSM4,          ensemble: r5i1p1}
  #     # - {dataset: CCSM4,          ensemble: r6i1p1}
  #     - {dataset: CNRM-CM5,       ensemble: r1i1p1}
  #     - {dataset: GFDL-CM3,       ensemble: r1i1p1}
  #     - {dataset: GFDL-ESM2G,     ensemble: r1i1p1}
  #     - {dataset: GFDL-ESM2M,     ensemble: r1i1p1}
  #     - {dataset: IPSL-CM5A-LR,   ensemble: r1i1p1}
  #     - {dataset: IPSL-CM5A-LR,   ensemble: r2i1p1}
  #     - {dataset: IPSL-CM5A-LR,   ensemble: r3i1p1}
  #     - {dataset: IPSL-CM5A-LR,   ensemble: r4i1p1}
  #     - {dataset: IPSL-CM5A-MR,   ensemble: r1i1p1}
  #     - {dataset: IPSL-CM5B-LR,   ensemble: r1i1p1}
  #     - {dataset: MIROC5,         ensemble: r1i1p1}
  #     - {dataset: MIROC5,         ensemble: r2i1p1}
  #     - {dataset: MIROC-ESM,      ensemble: r1i1p1}
  #     - {dataset: MIROC-ESM-CHEM, ensemble: r1i1p1}
  #     - {dataset: MPI-ESM-LR,     ensemble: r1i1p1}
  #     - {dataset: MPI-ESM-LR,     ensemble: r2i1p1}
  #     - {dataset: MPI-ESM-LR,     ensemble: r3i1p1}
  #     - {dataset: MPI-ESM-MR,     ensemble: r1i1p1}
  #     - {dataset: MPI-ESM-MR,     ensemble: r2i1p1}
  #     - {dataset: MPI-ESM-MR,     ensemble: r3i1p1}
  #   scripts:
  #     mean:
  #       <<: *mean
  #       tag: O3-SP_c
  #     trend:
  #       <<: *trend
  #       tag: O3-SP_t

  # diag_mlr_input_tro3_ng50:
  #   variables:
  #     tro3:
  #       <<: *variable_settings
  #       preprocessor: ng50
  #       additional_datasets:
  #         - {dataset: BDBP, project: OBS, type: reanaly, version: 1, tier: 3, var_type: prediction_input}
  #   additional_datasets: *tro3_datasets
  #   scripts:
  #     mean:
  #       <<: *mean
  #       tag: O3-NGlob_c
  #     trend:
  #       <<: *trend
  #       tag: O3-NGlob_t

  diag_mlr_input_uajet_sh850:
    variables:
      uajet:
        <<: *variable_settings
        preprocessor: djf
        derive: true
    additional_datasets: *datasets
    scripts:
      mean:
        <<: *mean
        tag: U-Jet_c
      trend:
        <<: *trend
        tag: U-Jet_t

  diag_mlr_input_tpp:
    variables:
      ta:
        <<: *variable_settings
        preprocessor: noop
    additional_datasets: *datasets
    scripts:
      mean: &tpp
        script: austral_jet/calc_tpp.ncl
        calc_type: mean
        tag: P-SH_c
        season: DJF
        lat_range: [-90, -50]
      trend:
        <<: *tpp
        calc_type: trend
        yearly_trend: true
        tag: P-SH_t

  diag_mlr_input_shhcb:
    variables:
      va:
        <<: *variable_settings
        preprocessor: noop
      ps:
        <<: *variable_settings
        preprocessor: noop
    additional_datasets: *datasets
    scripts:
      mean: &shhcb
        script: austral_jet/calc_shhcb.ncl
        calc_type: mean
        tag: H-SH_c
        season: DJF
        lat_range: [-80, -20]
        lev: 50000
      trend:
        <<: *shhcb
        calc_type: trend
        yearly_trend: true
        tag: H-SH_t

  diag_mlr_input_asr:
    variables:
      asr:
        <<: *variable_settings
        preprocessor: noop
        start_year: 2000
        derive: true
        additional_datasets:
          - {dataset: CERES-EBAF, project: obs4mips, level: L3B, version: Ed2-7, tier: 1, start_year: 2001, var_type: prediction_input}
    additional_datasets: *datasets
    scripts:
      mean:
        script: austral_jet/calc_asr.ncl
        tag: ASR-SH
        season: monthlyclim

  diag_mlr:
    description: Perform MLR on input data.
    variables:
      uajet:
        project: CMIP5
        mip: Amon
        exp: rcp45
        start_year: 2015
        end_year: 2034
        preprocessor: time_average_djf
        derive: true
        var_type: label
        tag: UAJET
    additional_datasets: *datasets
    scripts:
      mlr:
        script: mlr/main.py
        ancestors: [
          'uajet',
          'diag_mlr_input_*/mean',
          'diag_mlr_input_*/trend',
        ]
        mlr_model: gbr_sklearn
        accept_only_scalar_data: true
        group_datasets_by_attributes: ['dataset', 'ensemble']
        parameters_final_regressor:
          learning_rate: 0.001
          loss: ls
          max_depth: 4
          min_samples_split: 2
          n_estimators: 2000
