##############################################################################
# User's configuration file for the ESMValTool
# Manuel Schlund
# 2019-03-01
# DKRZ
###############################################################################
---

# Diagnostics create plots? [true]/false
write_plots: true
# Diagnositcs write NetCDF files? [true]/false
write_netcdf: true
# Set the console log level debug, [info], warning, error
log_level: info
# verbosity is deprecated and will be removed in the future
# verbosity: 1
# Exit on warning? true/[false]
exit_on_warning: false
# Plot file format? [ps]/pdf/png/eps/epsi
output_file_type: png
# Destination directory
output_dir: /scratch/b/b309165/automatization_output
# Auxiliary data directory (used for some additional datasets)
auxiliary_data_dir: ~/work/auxiliary_data
# Use netCDF compression true/[false]
compress_netcdf: false
# Save intermediary cubes in the preprocessor true/[false]
save_intermediary_cubes: false
# Remove the preproc dir if all fine
remove_preproc_dir: false
# Run at most this many tasks in parallel null/[1]/2/3/4/..
# Set to null to use the number of available CPUs.
# Make sure your system has enough memory for the specified number of tasks.
max_parallel_tasks: 4
# Path to custom config-developer file, to customise project configurations.
# See config-developer.yml for an example. Set to None to use the default
config_developer_file: null
# Get profiling information for diagnostics
# Only available for Python diagnostics
profile_diagnostic: false

# Rootpaths to the data from different projects (lists are also possible)
rootpath:
  CMIP5: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ
  CMIP6: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ/ #/mnt/lustre02/work/bd0854/CMIP6_DKRZ

  OBS: [
  # /mnt/lustre02/work/bd0854/DATA/ESMValTool1/OBS,
          /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS,
  # ~/work/obs,
  ]
  obs4mips: [
  # /mnt/lustre02/work/bd0854/DATA/ESMValTool1/OBS,
          /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS,
  # ~/work/obs,
  ]
  ana4mips: [
  # /mnt/lustre02/work/bd0854/DATA/ESMValTool1/OBS,
          /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS,
  # ~/work/obs,
  ]
  RAWOBS: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/RAWOBS
  default: /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS

# Directory structure for input data: [default]/BADC/DKRZ/ETHZ/etc
# See config-developer.yml for definitions.drs:
drs:
  CMIP5: DKRZ
  CMIP6: DKRZ
