# Conda build recipe
---

# Build command:
# conda build package -c conda-forge -c esmvalgroup

# Package version number
{% set version = "2.3.0" %}

package:
  name: esmvaltool
  version: {{ version }}

source:
  # Use these two lines to build a release:
  # git_rev: v{{ version }}
  # git_url: https://github.com/ESMValGroup/ESMValTool.git
  # Use this line instead of the above to test building without a release:
  path: ..

build:
  # Increment the build number when building a new conda package of the same
  # esmvaltool version, reset to 0 when building a new version.
  number: 0
  noarch: python

requirements:
  run:
    - python>=3.9
    - iris>=3.0.2
    - {{ pin_subpackage('esmvaltool-julia', exact=True) }}
    - {{ pin_subpackage('esmvaltool-ncl', exact=True) }}
    - {{ pin_subpackage('esmvaltool-python', exact=True) }}
    - {{ pin_subpackage('esmvaltool-r', exact=True) }}

test:
  source_files:
    - tests
    - setup.cfg
  requires:
    - pytest>=3.9,!=6.0.0rc1,!=6.0.0
    - pytest-cov
    - pytest-env
    - pytest-flake8
    - pytest-html!=2.1.0
    - pytest-metadata>=1.5.1
    - pytest-xdist
  imports:
    - esmvaltool
  commands:
    - pytest -n 2 --ignore="run_test.py" --ignore="tests/unit/test_docs.py"
    - cmorize_obs --help
    - nclcodestyle --help
    - esmvaltool colortables --help
    - test_recipe --help
    - ncl -V
    - cdo -V

outputs:

  - name: esmvaltool-python
    build:
      noarch: python
    script: install.sh
    requirements:
      build:
        - git
        - python>=3.9
        - setuptools_scm
      run:
        - cartopy>=0.18
        - cdo
        - eccodes>=2.19.1  # cdo dependency; something messed up with libeccodes.so
        # - cdsapii>=0.5.1
        - cf-units>=3.0
        - cftime>=1.2.1
        - cmocean>=2.0
        - cython
        - dask
        - ecmwf-api-client>=1.6.1  # in esmvalgroup channel
        - eofs>=1.4.0
        - esmpy>=8.0
        - esmvalcore>=2.3.1,<2.4  # in esmvalgroup channel
        - fiona>=1.8.18
        - gdal>=3.1
        - iris>=3.0.2
        - jinja2>=3.0.1
        - joblib>=1.0.1
        - lime
        - matplotlib>3.3.1,<3.4  # bug in 3.3.1, issue with nc-time-axis for >=3.4
        - mpich<3.4  # issues with 3.4.1 and 3.4.2 that install external_0 build
        - natsort>=7.1
        - nc-time-axis=1.2.0
        - netCDF4>=1.5.6
        - numpy>=1.21
        - pandas>=1.3.2
        - pyproj>=2.1
        - python>=3.9
        - python-cdo>=1.5.4
        - pyyaml>=5.4.1
        - ruamel.yaml>=0.17
        - rasterio>=1.2.6  # replaces pynio
        - scikit-image>=0.18
        - scikit-learn>=0.24
        - seaborn>=0.11
        - seawater>=3.3
        - shapely>=1.7
        - xarray>=0.19.0
        - xesmf>=0.3.0
        - xgboost>=1.4.2
        - xlsxwriter>=3.0

  - name: esmvaltool-julia
    build:
      noarch: generic
      post-link: install-julia-deps
    requirements:
      run:
        - esmvaltool-python

  - name: esmvaltool-ncl
    build:
      noarch: generic
    requirements:
      run:
        - cdo
        - esmvaltool-python
        - imagemagick
        - ncl>=6.6
        - nco

  - name: esmvaltool-r
    build:
      noarch: generic
      post-link: install-r-deps
    requirements:
      run:
        - cdo
        - compilers
        - esmvaltool-python
        - nco
        - r-base

about:
  home: https://www.esmvaltool.org
  license: Apache License, Version 2.0
  license_file: LICENSE
  summary: "A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP."
  description: "A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP."
